backend:
  name: github
  repo: EvaSpessotto/test-gatsby-netlify

media_folder: static/assets
public_folder: assets

publish_mode: editorial_workflow

collections:
  - name: posts
    label: Posts
    folder: blog
    create: true
    fields:
      - {name: path, label: Path }
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: author, label: Auteur }
      - { name: thumbnail, label: Miniature, widget: image}
      - { name: tags, label: Tags (séparer les tags par une virgule et un espace), widget: list }
      - { name: body, label: Body, widget: markdown }
  - name: pages
    label: Pages
    folder: pages-content
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      